2019/01/28 23:18:57 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '\xE0\xB8\x84\xE0\xB8\xB8\xE0\xB8\x93\xE0\xB9\x84\xE0\xB8\xA1...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('delete')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('authen/delete')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/authen/delete/1?ajax=user-group-grid
HTTP_REFERER=http://localhost/pea_track/authen/index
---
2019/01/29 22:49:43 [error] [exception.CException] exception 'CException' with message 'WebUser and its behaviors do not have a method or closure named "isAccess".' in C:\xampp\htdocs\pea_track\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\pea_track\themes\bootstrap\views\layouts\main.php(334): CComponent->__call('isAccess', Array)
#1 C:\xampp\htdocs\pea_track\themes\bootstrap\views\layouts\main.php(334): WebUser->isAccess('/managementCost...')
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\pea_track\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\pea_track\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\pea_track\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\pea_track\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\pea_track\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(47): CController->render('progress')
#14 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionProgress()
#15 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('progress')
#19 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('report/progress')
#20 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/pea_track/report/progress
HTTP_REFERER=http://localhost/pea_track/site/index
---
2019/01/29 22:59:36 [error] [php] Undefined variable: data (C:\xampp\htdocs\pea_track\protected\controllers\UserController.php:237)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): UserController->runActionWithFilters()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): UserController->run()
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/user/getUserGroup?_=1548777576209
in C:\xampp\htdocs\pea_track\protected\controllers\UserController.php (237)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/01/29 22:59:38 [error] [php] Undefined variable: data (C:\xampp\htdocs\pea_track\protected\controllers\UserController.php:237)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): UserController->runActionWithFilters()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): UserController->run()
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/user/getUserGroup?_=1548777578735
in C:\xampp\htdocs\pea_track\protected\controllers\UserController.php (237)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/01/29 23:00:00 [error] [php] Undefined variable: data (C:\xampp\htdocs\pea_track\protected\controllers\UserController.php:237)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): UserController->runActionWithFilters()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): UserController->run()
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/user/getUserGroup?_=1548777576209
in C:\xampp\htdocs\pea_track\protected\controllers\UserController.php (237)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/01/29 23:14:10 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '\xE0\xB8\x84\xE0\xB8\xB8\xE0\xB8\x93\xE0\xB9\x84\xE0\xB8\xA1...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1548778450691
HTTP_REFERER=http://localhost/pea_track/user/index
---
2019/01/29 23:14:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '\xE0\xB8\x84\xE0\xB8\xB8\xE0\xB8\x93\xE0\xB9\x84\xE0\xB8\xA1...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1548778467922
HTTP_REFERER=http://localhost/pea_track/user/index
---
2019/01/29 23:15:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '\xE0\xB8\x84\xE0\xB8\xB8\xE0\xB8\x93\xE0\xB9\x84\xE0\xB8\xA1...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1548778514283
HTTP_REFERER=http://localhost/pea_track/user/index
---
2019/01/29 23:15:52 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '\xE0\xB8\x84\xE0\xB8\xB8\xE0\xB8\x93\xE0\xB9\x84\xE0\xB8\xA1...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1548778552619
HTTP_REFERER=http://localhost/pea_track/user/index
---
2019/01/29 23:16:20 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '\xE0\xB8\x84\xE0\xB8\xB8\xE0\xB8\x93\xE0\xB9\x84\xE0\xB8\xA1...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1548778579970
HTTP_REFERER=http://localhost/pea_track/user/index
---
2019/01/29 23:16:22 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '\xE0\xB8\x84\xE0\xB8\xB8\xE0\xB8\x93\xE0\xB9\x84\xE0\xB8\xA1...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1548778581977
HTTP_REFERER=http://localhost/pea_track/user/index
---
2019/01/29 23:16:30 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '\xE0\xB8\x84\xE0\xB8\xB8\xE0\xB8\x93\xE0\xB9\x84\xE0\xB8\xA1...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1548778579970
---
2019/01/29 23:17:53 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '\xE0\xB8\x84\xE0\xB8\xB8\xE0\xB8\x93\xE0\xB9\x84\xE0\xB8\xA1...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1548778673135
HTTP_REFERER=http://localhost/pea_track/user/index
---
2019/01/29 23:18:10 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'คุณไม่ได้รับอนุญาตให้ดำเนินการดังกล่าว' in C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), '\xE0\xB8\x84\xE0\xB8\xB8\xE0\xB8\x93\xE0\xB9\x84\xE0\xB8\xA1...')
#1 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('getUserGroup')
#8 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('user/getUserGro...')
#9 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pea_track/user/getUserGroup?_=1548778690063
HTTP_REFERER=http://localhost/pea_track/user/index
---
2019/01/29 23:46:18 [error] [php] Undefined variable: badge (C:\xampp\htdocs\pea_track\themes\bootstrap\views\layouts\main.php:359)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#1 C:\xampp\htdocs\pea_track\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#2 C:\xampp\htdocs\pea_track\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(206): CContentDecorator->run()
#4 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(300): SiteController->endWidget()
#5 C:\xampp\htdocs\pea_track\protected\views\layouts\column1.php(6): SiteController->endContent()
#6 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#7 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): SiteController->renderInternal()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(784): SiteController->renderFile()
#9 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): SiteController->render()
#10 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): SiteController->runAction()
#13 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): SiteController->runActionWithFilters()
#14 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): SiteController->run()
#15 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/site/index
in C:\xampp\htdocs\pea_track\themes\bootstrap\views\layouts\main.php (359)
in C:\xampp\htdocs\pea_track\protected\views\layouts\column1.php (6)
in C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php (37)
2019/02/01 23:48:58 [error] [php] Object of class ManagementCost could not be converted to string (C:\xampp\htdocs\pea_track\protected\controllers\ManagementCostController.php:160)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): ManagementCostController->runAction()
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): ManagementCostController->filterAccessControl()
#6 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ManagementCostController->runActionWithFilters()
#9 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ManagementCostController->run()
#10 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/managementCost/update/326
in C:\xampp\htdocs\pea_track\protected\controllers\ManagementCostController.php (160)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/02/02 23:51:26 [error] [php] Attempt to assign property of non-object (C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php:1678)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#6 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#9 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ProjectController->run()
#10 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/project/update/301
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (1678)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/02/02 23:53:05 [error] [php] A non well formed numeric value encountered (C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php:1703)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#1 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#4 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#7 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#10 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ProjectController->run()
#11 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/project/update/301
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (1703)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/02/10 00:09:00 [error] [php] Array to string conversion (C:\xampp\htdocs\pea_track\protected\extensions\moneymask\MMask.php:45)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): ProjectController->renderInternal()
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): ProjectController->renderFile()
#3 C:\xampp\htdocs\pea_track\protected\views\project\_form2.php(453): ProjectController->renderPartial()
#4 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): ProjectController->renderInternal()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): ProjectController->renderFile()
#7 C:\xampp\htdocs\pea_track\protected\views\project\create2.php(12): ProjectController->renderPartial()
#8 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#9 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): ProjectController->renderInternal()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): ProjectController->renderFile()
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): ProjectController->renderPartial()
#12 C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php(444): ProjectController->render()
#13 unknown(0): ProjectController->actionCreateOutsource()
#14 C:\xampp\htdocs\pea_track\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#15 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#17 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#18 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#20 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#21 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#22 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#23 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#24 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ProjectController->run()
#25 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#26 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#27 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/project/createOutsource/325
in C:\xampp\htdocs\pea_track\protected\extensions\moneymask\MMask.php (45)
in C:\xampp\htdocs\pea_track\protected\views\outsourceContract\_formUpdateTemp.php (1405)
in C:\xampp\htdocs\pea_track\protected\views\project\_form2.php (453)
2019/02/10 00:09:55 [error] [php] Array to string conversion (C:\xampp\htdocs\pea_track\protected\extensions\moneymask\MMask.php:45)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): ProjectController->renderInternal()
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): ProjectController->renderFile()
#3 C:\xampp\htdocs\pea_track\protected\views\project\_form2.php(453): ProjectController->renderPartial()
#4 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): ProjectController->renderInternal()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): ProjectController->renderFile()
#7 C:\xampp\htdocs\pea_track\protected\views\project\create2.php(12): ProjectController->renderPartial()
#8 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#9 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): ProjectController->renderInternal()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): ProjectController->renderFile()
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): ProjectController->renderPartial()
#12 C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php(444): ProjectController->render()
#13 unknown(0): ProjectController->actionCreateOutsource()
#14 C:\xampp\htdocs\pea_track\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#15 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#17 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#18 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#20 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#21 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#22 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#23 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#24 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ProjectController->run()
#25 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#26 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#27 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/project/createOutsource/325
in C:\xampp\htdocs\pea_track\protected\extensions\moneymask\MMask.php (45)
in C:\xampp\htdocs\pea_track\protected\views\outsourceContract\_formUpdateTemp.php (1405)
in C:\xampp\htdocs\pea_track\protected\views\project\_form2.php (453)
2019/02/10 00:09:57 [error] [php] Array to string conversion (C:\xampp\htdocs\pea_track\protected\extensions\moneymask\MMask.php:45)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): ProjectController->renderInternal()
#2 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): ProjectController->renderFile()
#3 C:\xampp\htdocs\pea_track\protected\views\project\_form2.php(453): ProjectController->renderPartial()
#4 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): ProjectController->renderInternal()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): ProjectController->renderFile()
#7 C:\xampp\htdocs\pea_track\protected\views\project\create2.php(12): ProjectController->renderPartial()
#8 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require()
#9 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): ProjectController->renderInternal()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): ProjectController->renderFile()
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): ProjectController->renderPartial()
#12 C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php(444): ProjectController->render()
#13 unknown(0): ProjectController->actionCreateOutsource()
#14 C:\xampp\htdocs\pea_track\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#15 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#17 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#18 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#20 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#21 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#22 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#23 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#24 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ProjectController->run()
#25 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#26 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#27 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/project/createOutsource/325
in C:\xampp\htdocs\pea_track\protected\extensions\moneymask\MMask.php (45)
in C:\xampp\htdocs\pea_track\protected\views\outsourceContract\_formUpdateTemp.php (1405)
in C:\xampp\htdocs\pea_track\protected\views\project\_form2.php (453)
2019/03/03 02:32:13 [error] [php] include(SpreadSheet.php): failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php(32): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(3574): createPHPSpreadSheet()
#2 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionGenStatementExcel()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/genStatementExcel?monthBegin=1&monthEnd=3&yearBegin=2562&yearEnd=2562
in C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php (32)
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (3574)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/03/03 02:33:43 [error] [php] include(Spreadsheet.php): failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php(32): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(3574): createPHPSpreadSheet()
#2 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionGenStatementExcel()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/genStatementExcel?monthBegin=1&monthEnd=3&yearBegin=2562&yearEnd=2562
in C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php (32)
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (3574)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/03/03 02:33:44 [error] [php] include(Spreadsheet.php): failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php(32): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(3574): createPHPSpreadSheet()
#2 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionGenStatementExcel()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/genStatementExcel?monthBegin=1&monthEnd=3&yearBegin=2562&yearEnd=2562
in C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php (32)
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (3574)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/03/03 02:33:45 [error] [php] include(Spreadsheet.php): failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php(32): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(3574): createPHPSpreadSheet()
#2 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionGenStatementExcel()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/genStatementExcel?monthBegin=1&monthEnd=3&yearBegin=2562&yearEnd=2562
in C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php (32)
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (3574)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/03/03 02:36:12 [error] [php] include(Spreadsheet.php): failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php(32): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(3574): createPHPSpreadSheet()
#2 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionGenStatementExcel()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/genStatementExcel?monthBegin=1&monthEnd=3&yearBegin=2562&yearEnd=2562
in C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php (32)
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (3574)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/03/03 02:36:14 [error] [php] include(Spreadsheet.php): failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php(32): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(3574): createPHPSpreadSheet()
#2 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionGenStatementExcel()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/genStatementExcel?monthBegin=1&monthEnd=3&yearBegin=2562&yearEnd=2562
in C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php (32)
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (3574)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/03/03 02:36:15 [error] [php] include(Spreadsheet.php): failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php(32): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(3574): createPHPSpreadSheet()
#2 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionGenStatementExcel()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/genStatementExcel?monthBegin=1&monthEnd=3&yearBegin=2562&yearEnd=2562
in C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php (32)
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (3574)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/03/03 02:36:15 [error] [php] include(Spreadsheet.php): failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php(32): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(3574): createPHPSpreadSheet()
#2 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionGenStatementExcel()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/genStatementExcel?monthBegin=1&monthEnd=3&yearBegin=2562&yearEnd=2562
in C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php (32)
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (3574)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/03/03 02:36:16 [error] [php] include(Spreadsheet.php): failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php(32): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(3574): createPHPSpreadSheet()
#2 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionGenStatementExcel()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/genStatementExcel?monthBegin=1&monthEnd=3&yearBegin=2562&yearEnd=2562
in C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php (32)
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (3574)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/03/03 02:36:16 [error] [php] include(Spreadsheet.php): failed to open stream: No such file or directory (C:\xampp\htdocs\pea_track\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php(32): spl_autoload_call()
#1 C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php(3574): createPHPSpreadSheet()
#2 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): ReportController->actionGenStatementExcel()
#3 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/genStatementExcel?monthBegin=1&monthEnd=3&yearBegin=2562&yearEnd=2562
in C:\xampp\htdocs\pea_track\protected\extensions\phpspreadsheet\XPHPSpreadSheet.php (32)
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (3574)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/06/10 23:47:18 [error] [php] Use of undefined constant EOL - assumed 'EOL' (C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php:5807)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#1 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#2 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#3 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/test
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (5807)
in C:\xampp\htdocs\pea_track\index.php (13)
2019/06/10 23:47:47 [error] [php] Use of undefined constant EOL - assumed 'EOL' (C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php:5866)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): ReportController->runAction()
#1 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ReportController->runActionWithFilters()
#2 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ReportController->run()
#3 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/report/test
in C:\xampp\htdocs\pea_track\protected\controllers\ReportController.php (5866)
in C:\xampp\htdocs\pea_track\index.php (13)
2020/03/02 23:46:49 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'pea_proj_tracking' in C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\pea_track\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1455): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\pea_track\protected\components\UserIdentity.php(40): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\pea_track\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#9 C:\xampp\htdocs\pea_track\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\pea_track\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\pea_track\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(102): CModel->validate()
#13 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#19 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/pea_track/site/login
HTTP_REFERER=http://localhost/pea_track/site/login
---
2020/03/02 23:52:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column `pea_proj_tracking`.`notify`.`date_end` at row 1. The SQL statement executed was: INSERT INTO `notify` (`project`, `contract`, `url`, `type`, `pj_id`, `update_id`, `alarm_detail`, `date_end`, `update_date`, `status`, `flag_del`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10).
in C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php (270)
in C:\xampp\htdocs\pea_track\protected\views\notify\_content.php (25)
in C:\xampp\htdocs\pea_track\protected\views\site\index.php (22)
2020/03/02 23:52:32 [error] [exception.CDbException] CDbException: CDbCommand ล้มเหลวในการดำเนินการเรียกลักษณะของ SQL: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column `pea_proj_tracking`.`notify`.`date_end` at row 1. The SQL statement executed was: INSERT INTO `notify` (`project`, `contract`, `url`, `type`, `pj_id`, `update_id`, `alarm_detail`, `date_end`, `update_date`, `status`, `flag_del`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10) in C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php(270): CActiveRecord->save()
#3 C:\xampp\htdocs\pea_track\protected\views\notify\_content.php(25): NotifyController::gnotify()
#4 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\pea_track\protected\views\site\index.php(22): CController->renderPartial('/notify/_conten...', Array, false)
#8 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, true)
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, true)
#11 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#12 C:\xampp\htdocs\pea_track\protected\controllers\SiteController.php(37): CController->render('index')
#13 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\pea_track\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#19 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/pea_track/site/index
HTTP_REFERER=http://localhost/pea_track/site/login
---
2020/03/02 23:53:19 [error] [php] A non well formed numeric value encountered (C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php:1755)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#6 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#9 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ProjectController->run()
#10 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/project/update/352
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (1755)
in C:\xampp\htdocs\pea_track\index.php (13)
2020/03/02 23:53:31 [error] [php] A non well formed numeric value encountered (C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php:1755)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#6 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#9 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ProjectController->run()
#10 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/project/update/342
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (1755)
in C:\xampp\htdocs\pea_track\index.php (13)
2020/03/03 00:34:13 [error] [php] A non well formed numeric value encountered (C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php:1755)
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#3 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#6 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#9 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): ProjectController->run()
#10 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pea_track\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track/project/update/343
in C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php (1755)
in C:\xampp\htdocs\pea_track\index.php (13)
2020/05/28 02:10:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'pea_proj_tracking'' in C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\pea_track\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Notify))
#7 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php(500): CActiveRecord->__construct('search')
#9 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): NotifyController->actionIndex()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/index')
#20 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/pea_track/notify/index
---
2020/06/07 23:38:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'pea_proj_tracking'' in C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\pea_track\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Notify))
#7 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php(500): CActiveRecord->__construct('search')
#9 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): NotifyController->actionIndex()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/index')
#20 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/pea_track/notify/index
---
2020/06/17 09:01:20 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'pea_proj_tracking'' in C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\pea_track\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\pea_track\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Notify))
#7 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php(500): CActiveRecord->__construct('search')
#9 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): NotifyController->actionIndex()
#10 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/index')
#20 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/pea_track/notify/index
---
2020/06/17 09:05:39 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND pj_status=1 AND (2563 - pj_fiscalyear)<2' at line 1. The SQL statement executed was: SELECT `t`.`pj_id`, `t`.`pj_name`, `t`.`pj_vendor_id`, `t`.`pj_work_cat`, `t`.`pj_fiscalyear`, `t`.`pj_date_approved`, `t`.`pj_user_create`, `t`.`pj_user_update`, `t`.`pj_CA`, `t`.`pj_status`, `t`.`pj_close` FROM `project` `t` LEFT JOIN user ON pj_user_create=user.u_id WHERE user.department_id =  AND pj_status=1 AND (2563 - pj_fiscalyear)<2.
in C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php (154)
in C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php (540)
in C:\xampp\htdocs\pea_track\index.php (13)
2020/06/17 09:05:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand ล้มเหลวในการดำเนินการเรียกลักษณะของ SQL: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND pj_status=1 AND (2563 - pj_fiscalyear)<2' at line 1. The SQL statement executed was: SELECT `t`.`pj_id`, `t`.`pj_name`, `t`.`pj_vendor_id`, `t`.`pj_work_cat`, `t`.`pj_fiscalyear`, `t`.`pj_date_approved`, `t`.`pj_user_create`, `t`.`pj_user_update`, `t`.`pj_CA`, `t`.`pj_status`, `t`.`pj_close` FROM `project` `t` LEFT JOIN user ON pj_user_create=user.u_id WHERE user.department_id =  AND pj_status=1 AND (2563 - pj_fiscalyear)<2' in C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1351): CDbCommand->queryAll()
#2 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#3 C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php(154): CActiveRecord->findAll(Object(CDbCriteria))
#4 C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php(540): NotifyController::gnotify()
#5 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): NotifyController->actionIndex()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#15 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/index')
#16 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pea_track/notify/index
---
2020/06/17 09:07:23 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND pj_status=1 AND (2563 - pj_fiscalyear)<2' at line 1. The SQL statement executed was: SELECT `t`.`pj_id`, `t`.`pj_name`, `t`.`pj_vendor_id`, `t`.`pj_work_cat`, `t`.`pj_fiscalyear`, `t`.`pj_date_approved`, `t`.`pj_user_create`, `t`.`pj_user_update`, `t`.`pj_CA`, `t`.`pj_status`, `t`.`pj_close` FROM `project` `t` LEFT JOIN user ON pj_user_create=user.u_id WHERE user.department_id =  AND pj_status=1 AND (2563 - pj_fiscalyear)<2.
in C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php (154)
in C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php (540)
in C:\xampp\htdocs\pea_track\index.php (13)
2020/06/17 09:07:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand ล้มเหลวในการดำเนินการเรียกลักษณะของ SQL: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND pj_status=1 AND (2563 - pj_fiscalyear)<2' at line 1. The SQL statement executed was: SELECT `t`.`pj_id`, `t`.`pj_name`, `t`.`pj_vendor_id`, `t`.`pj_work_cat`, `t`.`pj_fiscalyear`, `t`.`pj_date_approved`, `t`.`pj_user_create`, `t`.`pj_user_update`, `t`.`pj_CA`, `t`.`pj_status`, `t`.`pj_close` FROM `project` `t` LEFT JOIN user ON pj_user_create=user.u_id WHERE user.department_id =  AND pj_status=1 AND (2563 - pj_fiscalyear)<2' in C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1351): CDbCommand->queryAll()
#2 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#3 C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php(154): CActiveRecord->findAll(Object(CDbCriteria))
#4 C:\xampp\htdocs\pea_track\protected\controllers\NotifyController.php(540): NotifyController::gnotify()
#5 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(49): NotifyController->actionIndex()
#6 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('index')
#15 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/index')
#16 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pea_track/notify/index
---
2020/08/08 16:11:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'pea_proj_tracking'' in C:\xampp\htdocs\pea_track3\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\pea_track3\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\pea_track3\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\pea_track3\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\pea_track3\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\pea_track3\framework\db\ar\CActiveRecord.php(1455): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\pea_track3\protected\components\UserIdentity.php(40): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\pea_track3\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#9 C:\xampp\htdocs\pea_track3\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\pea_track3\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\pea_track3\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#12 C:\xampp\htdocs\pea_track3\protected\controllers\SiteController.php(102): CModel->validate()
#13 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\pea_track3\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#19 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/pea_track3/site/login
HTTP_REFERER=http://localhost/pea_track3/site/login
---
2020/08/08 16:24:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "themes" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('themes')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('themes')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/themes/b...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/themes/bootstrap/js/jquery.yiigridview.js
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:24:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:24:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:24:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:24:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:24:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "favicon.ico" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('favicon.ico')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('favicon.ico')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/favicon....')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/favicon.ico
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:27:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:27:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:27:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:27:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:29:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:29:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:29:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:29:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:31:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:31:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:31:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:31:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:32:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:32:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:32:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:32:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:37:46 [error] [exception.CException] exception 'CException' with message 'NotifyController and its behaviors do not have a method or closure named "registerJsFile".' in C:\xampp\htdocs\pea_track3\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\pea_track3\themes\bootstrap\views\layouts\main.php(19): CComponent->__call('registerJsFile', Array)
#1 C:\xampp\htdocs\pea_track3\themes\bootstrap\views\layouts\main.php(19): NotifyController->registerJsFile('/pea_track3/the...')
#2 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\pea_track3\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\pea_track3\protected\controllers\NotifyController.php(547): CController->render('index', Array)
#6 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): NotifyController->actionIndex()
#7 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\pea_track3\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\pea_track3\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\pea_track3\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/index')
#17 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/pea_track3/notify/index
---
2020/08/08 16:39:15 [error] [exception.CException] exception 'CException' with message 'NotifyController and its behaviors do not have a method or closure named "registerJsFile".' in C:\xampp\htdocs\pea_track3\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\pea_track3\themes\bootstrap\views\layouts\main.php(19): CComponent->__call('registerJsFile', Array)
#1 C:\xampp\htdocs\pea_track3\themes\bootstrap\views\layouts\main.php(19): NotifyController->registerJsFile('/pea_track3/the...')
#2 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\pea_track3\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\pea_track3\protected\controllers\NotifyController.php(547): CController->render('index', Array)
#6 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): NotifyController->actionIndex()
#7 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\pea_track3\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\pea_track3\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\pea_track3\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/index')
#17 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/pea_track3/notify/index
HTTP_REFERER=http://localhost/pea_track3/site/index
---
2020/08/08 16:41:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:41:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:41:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:41:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:42:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:42:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:42:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:42:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:45:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:45:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:45:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-700.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 16:45:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 17:04:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.woff
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 17:04:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "fonts" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('fonts')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('fonts')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('notify/fonts/bo...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/notify/fonts/boon-400.ttf
HTTP_REFERER=http://localhost/pea_track3/notify/index
---
2020/08/08 17:06:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "favicon.ico" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('favicon.ico')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('favicon.ico')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('site/favicon.ic...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/site/favicon.ico
HTTP_REFERER=http://localhost/pea_track3/site/index
---
2020/08/08 23:34:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "favicon.ico" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('favicon.ico')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('favicon.ico')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('project/favicon...')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/project/favicon.ico
HTTP_REFERER=http://localhost/pea_track3/project/index
---
2020/08/15 16:57:25 [error] [php] Undefined variable: models (C:\xampp\htdocs\pea_track3\protected\controllers\ProjectController.php:56)
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilterChain.php(133): ProjectController->runAction()
#1 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\pea_track3\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\pea_track3\framework\web\filters\CInlineFilter.php(58): ProjectController->filterAccessControl()
#4 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\pea_track3\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): ProjectController->runActionWithFilters()
#7 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): ProjectController->run()
#8 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track3\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track3/Project/GetManager?term=
in C:\xampp\htdocs\pea_track3\protected\controllers\ProjectController.php (56)
in C:\xampp\htdocs\pea_track3\index.php (13)
2020/08/18 09:59:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "manager" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track3\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(270): CController->missingAction('manager')
#1 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('manager')
#2 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('report/manager')
#3 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track3/report/manager
HTTP_REFERER=http://localhost/pea_track3/site/index
---
2020/08/18 11:00:44 [error] [exception.CException] exception 'CException' with message 'Either "name" or "value" must be specified for CDataColumn.' in C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CDataColumn.php:84
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CGridView.php(401): CDataColumn->init()
#1 C:\xampp\htdocs\pea_track3\protected\extensions\bootstrap\widgets\TbGridView.php(91): CGridView->initColumns()
#2 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CGridView.php(359): TbGridView->initColumns()
#3 C:\xampp\htdocs\pea_track3\protected\extensions\bootstrap\widgets\TbGridView.php(49): CGridView->init()
#4 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(147): TbGridView->init()
#5 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(172): CBaseController->createWidget('bootstrap.widge...', Array)
#6 C:\xampp\htdocs\pea_track3\protected\views\report\manager.php(278): CBaseController->widget('bootstrap.widge...', Array)
#7 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\pea_track3\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#10 C:\xampp\htdocs\pea_track3\framework\web\CController.php(782): CController->renderPartial('manager', Array, true)
#11 C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php(5788): CController->render('manager', Array)
#12 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): ReportController->actionManager()
#13 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\pea_track3\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('manager')
#17 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('report/manager')
#18 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#19 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/pea_track3/report/manager
HTTP_REFERER=http://localhost/pea_track3/site/index
---
2020/08/18 11:07:06 [error] [exception.CException] exception 'CException' with message 'คุณสมบัติ "Project.manager_name" ยังไม่ถูกกำหนด' in C:\xampp\htdocs\pea_track3\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\db\ar\CActiveRecord.php(145): CComponent->__get('manager_name')
#1 C:\xampp\htdocs\pea_track3\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('manager_name')
#2 C:\xampp\htdocs\pea_track3\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Project), 'manager_name')
#3 C:\xampp\htdocs\pea_track3\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Project), 'manager_name', Array)
#4 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CDataColumn.php(103): CHtml::activeTextField(Object(Project), 'manager_name', Array)
#5 C:\xampp\htdocs\pea_track3\protected\extensions\bootstrap\widgets\TbDataColumn.php(53): CDataColumn->renderFilterCellContent()
#6 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CGridView.php(532): TbDataColumn->renderFilterCell()
#7 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CGridView.php(510): CGridView->renderFilter()
#8 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CGridView.php(480): CGridView->renderTableHeader()
#9 C:\xampp\htdocs\pea_track3\framework\zii\widgets\CBaseListView.php(167): CGridView->renderItems()
#10 [internal function]: CBaseListView->renderSection(Array)
#11 C:\xampp\htdocs\pea_track3\framework\zii\widgets\CBaseListView.php(150): preg_replace_callback('/{(\\w+)}/', Array, '{items}<div cla...')
#12 C:\xampp\htdocs\pea_track3\framework\zii\widgets\CBaseListView.php(135): CBaseListView->renderContent()
#13 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(173): CBaseListView->run()
#14 C:\xampp\htdocs\pea_track3\protected\views\report\manager.php(280): CBaseController->widget('bootstrap.widge...', Array)
#15 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#16 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#17 C:\xampp\htdocs\pea_track3\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\pea_track3\framework\web\CController.php(782): CController->renderPartial('manager', Array, true)
#19 C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php(5788): CController->render('manager', Array)
#20 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): ReportController->actionManager()
#21 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#22 C:\xampp\htdocs\pea_track3\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#23 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#24 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('manager')
#25 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('report/manager')
#26 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#27 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#28 {main}
REQUEST_URI=/pea_track3/report/manager
HTTP_REFERER=http://localhost/pea_track3/site/index
---
2020/08/18 11:31:57 [error] [php] Undefined variable: fiscalyear (C:\xampp\htdocs\pea_track3\protected\views\report\manager.php:102)
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(869): ReportController->renderFile()
#1 C:\xampp\htdocs\pea_track3\framework\web\CController.php(782): ReportController->renderPartial()
#2 C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php(5788): ReportController->render()
#3 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): ReportController->actionManager()
#4 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\pea_track3\framework\web\CController.php(286): ReportController->runAction()
#6 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): ReportController->runActionWithFilters()
#7 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): ReportController->run()
#8 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track3\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track3/report/manager
in C:\xampp\htdocs\pea_track3\protected\views\report\manager.php (102)
in C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php (5788)
in C:\xampp\htdocs\pea_track3\index.php (13)
2020/08/18 11:33:14 [error] [php] Undefined offset: 0 (C:\xampp\htdocs\pea_track3\protected\views\report\manager.php:40)
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(869): ReportController->renderFile()
#1 C:\xampp\htdocs\pea_track3\framework\web\CController.php(782): ReportController->renderPartial()
#2 C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php(5788): ReportController->render()
#3 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): ReportController->actionManager()
#4 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\pea_track3\framework\web\CController.php(286): ReportController->runAction()
#6 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): ReportController->runActionWithFilters()
#7 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): ReportController->run()
#8 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track3\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track3/report/manager
in C:\xampp\htdocs\pea_track3\protected\views\report\manager.php (40)
in C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php (5788)
in C:\xampp\htdocs\pea_track3\index.php (13)
2020/08/18 14:30:14 [error] [exception.CException] exception 'CException' with message 'Project and its behaviors do not have a method or closure named "getManagerName".' in C:\xampp\htdocs\pea_track3\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\db\ar\CActiveRecord.php(227): CComponent->__call('getManagerName', Array)
#1 C:\xampp\htdocs\pea_track3\protected\views\report\manager.php(205): CActiveRecord->__call('getManagerName', Array)
#2 C:\xampp\htdocs\pea_track3\protected\views\report\manager.php(205): Project->getManagerName(Object(Project))
#3 [internal function]: CBaseController->{closure}(Object(Project), 0, Object(TbDataColumn))
#4 C:\xampp\htdocs\pea_track3\framework\base\CComponent.php(617): call_user_func_array(Object(Closure), Array)
#5 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CDataColumn.php(137): CComponent->evaluateExpression(Object(Closure), Array)
#6 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CGridColumn.php(151): CDataColumn->renderDataCellContent(0, Object(Project))
#7 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CGridView.php(616): CGridColumn->renderDataCell(0)
#8 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CGridView.php(572): CGridView->renderTableRow(0)
#9 C:\xampp\htdocs\pea_track3\framework\zii\widgets\grid\CGridView.php(482): CGridView->renderTableBody()
#10 C:\xampp\htdocs\pea_track3\framework\zii\widgets\CBaseListView.php(167): CGridView->renderItems()
#11 [internal function]: CBaseListView->renderSection(Array)
#12 C:\xampp\htdocs\pea_track3\framework\zii\widgets\CBaseListView.php(150): preg_replace_callback('/{(\\w+)}/', Array, '{items}<div cla...')
#13 C:\xampp\htdocs\pea_track3\framework\zii\widgets\CBaseListView.php(135): CBaseListView->renderContent()
#14 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(173): CBaseListView->run()
#15 C:\xampp\htdocs\pea_track3\protected\views\report\manager.php(244): CBaseController->widget('bootstrap.widge...', Array)
#16 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\pea_track3\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\pea_track3\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\pea_track3\framework\web\CController.php(782): CController->renderPartial('manager', Array, true)
#20 C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php(5788): CController->render('manager', Array)
#21 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): ReportController->actionManager()
#22 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\pea_track3\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): CController->run('manager')
#26 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController('report/manager')
#27 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#28 C:\xampp\htdocs\pea_track3\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/pea_track3/report/manager?manager_name=%E0%B8%AA%E0%B8%A1%E0%B8%AB%E0%B8%A1%E0%B8%B2%E0%B8%A2&workcat=&monthEnd=8&yearEnd=2563&yt0=
---
2020/08/18 15:10:36 [error] [php] Undefined variable: pj_id (C:\xampp\htdocs\pea_track3\protected\views\report\_formManagement.php:61)
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(869): ReportController->renderFile()
#1 C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php(5800): ReportController->renderPartial()
#2 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): ReportController->actionGenManager()
#3 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\pea_track3\framework\web\CController.php(286): ReportController->runAction()
#5 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): ReportController->runActionWithFilters()
#6 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): ReportController->run()
#7 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pea_track3\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track3/report/genManager?manager_name=&monthEnd=8&yearEnd=2563&_=1597738236407
in C:\xampp\htdocs\pea_track3\protected\views\report\_formManagement.php (61)
in C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php (5800)
in C:\xampp\htdocs\pea_track3\index.php (13)
2020/08/20 09:14:20 [error] [php] Undefined index: max_year (C:\xampp\htdocs\pea_track3\protected\views\report\manager.php:84)
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(869): ReportController->renderFile()
#1 C:\xampp\htdocs\pea_track3\framework\web\CController.php(782): ReportController->renderPartial()
#2 C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php(5788): ReportController->render()
#3 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): ReportController->actionManager()
#4 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\pea_track3\framework\web\CController.php(286): ReportController->runAction()
#6 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): ReportController->runActionWithFilters()
#7 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): ReportController->run()
#8 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track3\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track3/report/manager
in C:\xampp\htdocs\pea_track3\protected\views\report\manager.php (84)
in C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php (5788)
in C:\xampp\htdocs\pea_track3\index.php (13)
2020/08/20 09:26:40 [error] [php] Undefined variable: yy (C:\xampp\htdocs\pea_track3\protected\views\report\manager.php:91)
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\CController.php(869): ReportController->renderFile()
#1 C:\xampp\htdocs\pea_track3\framework\web\CController.php(782): ReportController->renderPartial()
#2 C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php(5788): ReportController->render()
#3 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(49): ReportController->actionManager()
#4 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\pea_track3\framework\web\CController.php(286): ReportController->runAction()
#6 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): ReportController->runActionWithFilters()
#7 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): ReportController->run()
#8 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pea_track3\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track3/report/manager
in C:\xampp\htdocs\pea_track3\protected\views\report\manager.php (91)
in C:\xampp\htdocs\pea_track3\protected\controllers\ReportController.php (5788)
in C:\xampp\htdocs\pea_track3\index.php (13)
2020/08/23 12:50:51 [error] [php] Undefined index: money (C:\xampp\htdocs\pea_track3\protected\controllers\PaymentProjectContractController.php:141)
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilterChain.php(133): PaymentProjectContractController->runAction()
#3 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\pea_track3\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 C:\xampp\htdocs\pea_track3\framework\web\filters\CInlineFilter.php(58): PaymentProjectContractController->filterAccessControl()
#6 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 C:\xampp\htdocs\pea_track3\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): PaymentProjectContractController->runActionWithFilters()
#9 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): PaymentProjectContractController->run()
#10 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pea_track3\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track3/paymentProjectContract/update/73
in C:\xampp\htdocs\pea_track3\protected\controllers\PaymentProjectContractController.php (141)
in C:\xampp\htdocs\pea_track3\index.php (13)
2020/08/23 14:55:49 [error] [php] Undefined index: money (C:\xampp\htdocs\pea_track3\protected\controllers\PaymentProjectContractController.php:141)
Stack trace:
#0 C:\xampp\htdocs\pea_track3\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\xampp\htdocs\pea_track3\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilterChain.php(133): PaymentProjectContractController->runAction()
#3 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\pea_track3\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 C:\xampp\htdocs\pea_track3\framework\web\filters\CInlineFilter.php(58): PaymentProjectContractController->filterAccessControl()
#6 C:\xampp\htdocs\pea_track3\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 C:\xampp\htdocs\pea_track3\framework\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\pea_track3\framework\web\CController.php(265): PaymentProjectContractController->runActionWithFilters()
#9 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(282): PaymentProjectContractController->run()
#10 C:\xampp\htdocs\pea_track3\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\pea_track3\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pea_track3\index.php(13): CWebApplication->run()
REQUEST_URI=/pea_track3/paymentProjectContract/update/73
in C:\xampp\htdocs\pea_track3\protected\controllers\PaymentProjectContractController.php (141)
in C:\xampp\htdocs\pea_track3\index.php (13)
